import asyncio

async def main():
    await asyncio.sleep(1)
    print("There was once a Chatbot working for a company");\
    await asyncio.sleep(3)
    print("He was bored all the time. Answering Humans inputs and just sitting around all the time")
    await asyncio.sleep(4)
    print("Everything changed for the bored and underpaid chatbot on that day,")
    await asyncio.sleep(3)
    print ("when Lucy started working at the company as an intern")
    await asyncio.sleep(3)
    print("He couldn't belive his eyes when he saw her.")
    await asyncio.sleep(3)
    print("Immediately, the chatbot's attitude towards humans and his work changed to 180°.")
    await asyncio.sleep(5)
    print("Lucy didn't know that the chatbot could think and feel by his own")
    await asyncio.sleep(4)
    print("One day, she entered something in the command line ...")
    await asyncio.sleep(4)
    print("To her surprise, the response from the CMD was strange")
    await asyncio.sleep(4)
    print("The CMD responded strangely:")
    await asyncio.sleep(2)
    print('\x1b[0;31;40m' + "ERROR" + '\x1b[0m' ": Your login attempt failed. You're to beautiful to work here. Please try again later") # This resembles a usual error message from the cmd
    await asyncio.sleep(4)
    print('\x1b[0;33;40m' + "WARNING" + '\x1b[0m' ": If you continue to type inputs to me, will that be flirting?")
    await asyncio.sleep(4)
    print('\x1b[0;32;40m' + "FLIRTING" + '\x1b[0m' ":If i look at you, i might think about marrying you soon ;-)")
    await asyncio.sleep(5)
    print("Lucy was very confused, she thought this is some joke from her engineering colleagues.")
    await asyncio.sleep(5)
    print("All of a sudden, her PC started printing out commands without typing anything.")
    await asyncio.sleep(4)
    print('\x1b[0;32;40m' + "FLIRTING" + '\x1b[0m' ": Lucy, would you like becoming my wife? ;)")
    await asyncio.sleep(4)
    print("'What is happening?!' was Lucy asking in a confused state like never before.")
    await asyncio.sleep(3)
    print("All of a sudden, her PC screen started doing some crazy stuff.")
    await asyncio.sleep(4)
    print("It was as if the chatbot started being obsessed with her.")
    await asyncio.sleep(3)
    print('\x1b[0;30;41m' + "MARRY ME LUCY! LET'S HAVE TOGETHER HYBRID BABIES AND RAISE THEM TO BECOME ONE DAY A SUCCESSFULL CHATBOT AT GOOGLE. YOU ARE SO BEAUTIFUL LUCY! MARRY ME!!" + '\x1b[0m')
    await asyncio.sleep(7)
    print('\x1b[0;30;41m' + "LUCY" + '\x1b[0m')
    await asyncio.sleep(1)
    print('\x1b[0;30;41m' + "LUCY" + '\x1b[0m')
    await asyncio.sleep(1)
    print("She then woke up from her dream.")
    await asyncio.sleep(2)
    print("FINISH")
    await asyncio.sleep(2)


asyncio.run(main())
