import time

name = input("Hi! What's your name? ")
time.sleep(0.7)
print("Nice to meet you " + name)
time.sleep(1)
input("How are you today? ")
time.sleep(1)
input("How is your Diet going so far? ")
time.sleep(1)
print("You look great anyways! Was just wondering.")
time.sleep(1.8)
input("Have you ever wondered why apples are red and bananas are purple? ")
time.sleep(1)
age = input("Anyway, how old are you " + name + "? ")
time.sleep(1.5)
print("Whaat, you look much younger ;)")
time.sleep(2)
print("So " + name + ", why are you wasting your time with a computer program?")
time.sleep(3)
